//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyGloveShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materials
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Materials()
        {
            this.MaterialToSupplier = new HashSet<MaterialToSupplier>();
        }
    
        public int IdMaterial { get; set; }
        public string NameMaterial { get; set; }
        public int IdTypeMaterial { get; set; }
        public string Photo { get; set; }
        public decimal Price { get; set; }
        public int CountOnWarehouse { get; set; }
        public int MinCount { get; set; }
        public int CountPackaging { get; set; }
        public int IdTypeUnit { get; set; }
        public string Description { get; set; }
    
        public virtual TypeMaterial TypeMaterial { get; set; }
        public virtual TypeUnit TypeUnit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialToSupplier> MaterialToSupplier { get; set; }
    }
}
