//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyGloveShop.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoryMaterialsOnWarehouse
    {
        public int IdChange { get; set; }
        public int IdMaterial { get; set; }
        public int CountOnWareHouse { get; set; }
        public System.DateTime Datetime { get; set; }
    }
}
