//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyGloveShop.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Suppliers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Suppliers()
        {
            this.MaterialToSupplier = new HashSet<MaterialToSupplier>();
        }
    
        public int IdSupplier { get; set; }
        public string NameSupplier { get; set; }
        public int IdTypeSupplier { get; set; }
        public string INN { get; set; }
        public int Raiting { get; set; }
        public System.DateTime StartDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialToSupplier> MaterialToSupplier { get; set; }
        public virtual TypeSupplier TypeSupplier { get; set; }
    }
}
